[package]
name    = "kaseddie_cairo_foundations"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.0"

[dev-dependencies]
snforge_std = "0.49.0"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[[target.starknet-contract]]
name = "uservault"
path   = "src/uservault.cairo"
sierra = true
casm = true